husky test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,5 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
 
-npm run lint
+npm run lint || {
+  echo "Linting failed. Please fix the issues before committing."
+  exit 1
+}
